# Generated by Django 4.1 on 2022-08-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Usersend',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
