# Generated by Django 4.1 on 2022-08-20 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=25, null=True, verbose_name='Rol')),
                ('TiempoEntrada', models.DateTimeField()),
                ('TiempoSalida', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assistance', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('dni', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rol')),
            ],
        ),
    ]
