# Generated by Django 4.1 on 2022-08-21 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistance',
            old_name='rol',
            new_name='assistance_rol',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='rol',
            new_name='rol_name',
        ),
    ]
