# Generated by Django 4.1 on 2022-08-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_assistance_assistance_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='assistance_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rol'),
        ),
    ]
