# Generated by Django 4.1 on 2022-08-21 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_rol_assistance_assistance_rol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistance',
            old_name='dni',
            new_name='assistance_dni',
        ),
    ]
